### ISSUE TITLE
Decrypt HTTPS traffic ?

### ISSUE THREAD

**Issue by phil-lgr** [attdevsupport/ARO#18]
Hey AT&T, thank you for providing this tool, I am a front end dev and it helps a lot.

Is there any way to decrypt HTTPS traffic ? I guess we can`t since it would require installing some sort of root certificate on iOS/Android devices ?

Thank you,

Phil

**Comment by dougsillars** [comment]
Phil, 

Great  minds think alike!

Look for secure collection  in ARO 6.0 coming late December. It will require a custom cert, and is currently Android kitkat nly (hopefully we'll get more support p and running befote release).

Also, this  code will not be a part of the open source release, but we will have APIs that will allow access to the functionality.

Doug
